services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    pull_policy: always
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100